### ISSUE TITLE
Module not found: Can't resolve `'fs'`

### ISSUE THREAD

**Issue by DevDario** [vercel/next-learn#125] opened 2023-08-21 19:15 UTC
it appears that next cant find the `fs` module, but I've imported this module in the specified file 🤷🏻‍♂️

![nextjsblog-issue](https://github.com/vercel/next-learn/assets/101002847/3f062b6f-768d-4e88-a347-17ae8f232bd3)

**Comment by patrickromo1** [comment] 2023-09-23 17:58
It throws this error if you do not have the `getStaticProps` function in your `pages/posts/[id].js` file.
If you think you do have it you should double check the function name for a typo.

**Comment by DevDario** [comment] 2023-09-23 18:14
@patrickromo1 i'm going to check it out, thanks for the reply

**Comment by DevDario** [comment] 2023-09-23 20:14
@patrickromo1 I checked and, I actually have the  `getStaticProps` method in my code

**Comment by patrickromo1** [comment] 2023-09-23 20:37
@DevDario Dang I had the error you had which led me here and that fixed it for me.

For what it's worth I was able to finish the tutorial so I don't think it's an all encompassing bug in the tutorial.

**Comment by DevDario** [comment] 2023-09-23 20:45
But Thanks, @patrickromo1, I'll keep trying

**Comment by manovotny** [comment] 2023-09-27 22:24
@DevDario what part of the course are you in? Can you toss a link?

**Comment by josephrmartinez** [comment] 2023-10-21 17:56
@DevDario  I was following the tutorial and also getting the same error at this page: https://nextjs.org/learn/basics/dynamic-routes/implement-getstaticprops

Right at the line:
"That’s it! Try visiting these pages:

http://localhost:3000/posts/ssg-ssr
http://localhost:3000/posts/pre-rendering
You should be able to see the blog data for each page:"

I saw the error as indicated above. 

The problem is that my [id].js file looked like this:
import Layout from '../../components/layout';
import { getAllPostIds, getPostData } from '../../lib/posts';

export async function getStaticProps({ params }) {
  const postData = getPostData(params.id);
  return {
    props: {
      postData,
    },
  };
}

export default function Post({ postData }) {
    return (
      <Layout>
        {postData.title}
        <br />
        {postData.id}
        <br />
        {postData.date}
      </Layout>
    );
  }
  
  I was completely missing code from the previous page:
  export async function getStaticPaths() {
  const paths = getAllPostIds();
  return {
    paths,
    fallback: false,
  };
}

I was able to figure out my mistake with the resources linked further down in that section:

Something Wrong?
If you come across an error, make sure your files have the correct code:

pages/posts/[id].js should [look like this](https://github.com/vercel/next-learn/blob/main/basics/dynamic-routes-step-1/pages/posts/%5Bid%5D.js).
lib/posts.js should [look like this](https://github.com/vercel/next-learn/blob/main/basics/dynamic-routes-step-1/lib/posts.js).
(If it’s still not working) The remaining code should [look like this](https://github.com/vercel/next-learn/tree/main/basics/dynamic-routes-step-1).
  
Were you able to resolve the issue and complete the tutorial?

**Comment by delbaoliveira** [comment] 2023-11-17 09:55
Thank you for the answer @josephrmartinez 🙏🏼 

Closing the issue for now, @DevDario please let us know if you continue to experience it. Happy to look at a reproduction.

**Closed by delbaoliveira** 2023-11-17 09:55 UTC
