### ISSUE TITLE
Chapter 6 Create Database before Deploying

### ISSUE THREAD

**Issue by uxfed** [vercel/next-learn#780] opened 2024-07-01 02:35 UTC
In Chapter 6, if you Deploy before creating a database, the build fails.

"VercelPostgresError - 'missing_connection_string': You did not supply a 'connectionString' and no 'POSTGRES_URL' env var was found."

https://github.com/orgs/vercel/discussions/7332

Suggest swapping the order of those two steps in the tutorial. Create database, then deploy. Then it works.

**Comment by dhruv1210** [comment] 2024-07-02 05:48
![just now](https://github.com/vercel/next-learn/assets/104168747/a2c9b332-db10-42af-94ac-6593dbf258d5)
I am facing this issue while seed your database. please help me out with this (in lecture 6)

**Comment by ImTemane** [comment] 2024-07-02 07:25
Hi dhruv1210, its simple to fix this error:

First, you need to create a PostgreDB : https://nextjs.org/learn/dashboard-app/setting-up-your-database#create-a-postgres-database

Then you need to seed and explore your DB : https://nextjs.org/learn/dashboard-app/setting-up-your-database#seed-your-database

thengo to this section : https://nextjs.org/learn/dashboard-app/setting-up-your-database#executing-queries

_**And finally,**_  you can deploy your Next.js project on Vercel !!! (You need to do this for this project) : https://vercel.com

_Or you can just execute_ `pnpm dev`

**Comment by nguyenmp** [comment] 2024-07-04 02:54
Probably duplicate of https://github.com/vercel/next-learn/issues/780

**Comment by leerob** [comment] 2024-07-06 03:20
Fixed to give more specific information to uncomment this file and then delete it after: https://github.com/vercel/next-learn/commit/d379162091cac7ea4d0e3054a9fb527c00596264

**Closed by leerob** 2024-07-06 03:20 UTC

**Comment by Yxiongwu** [comment] 2024-07-21 11:30
> Fixed to give more specific information to uncomment this file and then delete it after: [d379162](https://github.com/vercel/next-learn/commit/d379162091cac7ea4d0e3054a9fb527c00596264)

Thank you, the problem is solved! By the way, this should really be changed in the official learning documentation.
