### ISSUE TITLE
Chapter 6: Cannot seed database

### ISSUE THREAD

**Issue by daweed311** [vercel/next-learn#484] opened 2023-11-25 17:27 UTC
Hi Team,

I trust this message finds you in good spirits. 🌟 Your commitment to the project is truly appreciated, and we welcome your active involvement.

We've identified an issue post-seeding the database. Although the storage isn't empty, there are discrepancies we need your expertise to address:

<img width="696" alt="image" src="https://github.com/vercel/next-learn/assets/80812123/e188722f-dabc-4e78-ae5a-58c54b6b08ee">

Description: After seeding the database, non-empty storage is observed.

However, when checking the tables list, it appears to be empty, and the connection status remains stuck at Connecting:

<img width="1012" alt="image" src="https://github.com/vercel/next-learn/assets/80812123/2d56b9d4-7817-4153-b3c9-1f5a359ea9b6">

This discrepancy is hindering the expected behavior of the system. We would greatly appreciate your insights and contributions to resolve this issue.

Details:

Issue Title: Database Seeding Discrepancy
Description: Non-empty storage, yet tables list is empty, and connection status is Connecting.

Thank you for your ongoing support!

**Comment by daweed311** [comment] 2023-11-27 18:16
Actually issue is reproducing on macOS, while on windows I can see `Connected` status in Storage -> Dashobard -> Data

**Comment by delbaoliveira** [comment] 2023-11-28 10:42
Thank you for reporting this @daweed311, are you still seeing this issue in the Vercel dashboard?

**Comment by daweed311** [comment] 2023-11-28 18:24
Yes, only on macOS device

**Comment by Bashtiani** [comment] 2023-11-28 23:25
I am experiencing the same issue on Windows in addition to the missing_connecting_string error after running the seeding command. 

An error occurred while attempting to seed the database: VercelPostgresError: VercelPostgresError - 'missing_connection_string': You did not supply a 'connectionString' and no 'POSTGRES_URL' env var was found.

**Comment by N-Besnard** [comment] 2023-12-07 14:02
Hi ! 

Just rename .env.local to .env worked for me

**Comment by Kuldeep-truefan** [comment] 2023-12-11 10:09
$ npm run seed

> seed
> node -r dotenv/config ./scripts/seed.js

node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND ep-cool-butterfly-22386990-pooler.ap-southeast-1.postgres.vercel-storage.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (D:\projects\nextjs-dashboard\node_modules\ws\lib\websocket.js:1016:13)
    at ClientRequest.<anonymous> (D:\projects\nextjs-dashboard\node_modules\ws\lib\websocket.js:864:5)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'ep-cool-butterfly-22386990-pooler.ap-southeast-1.postgres.vercel-storage.com'
}

Node.js v18.17.0

**Comment by MezgebuMeseret1** [comment] 2024-01-10 07:14
> Hi !
> 
> Just rename .env.local to .env worked for me
I did. But not working for me

**Comment by warrengoldman** [comment] 2024-01-31 21:58
Having similiar issue (please note this issue is not the connection string issue, slightly different). This symptom has been sited 3 times now
- https://github.com/vercel/next-learn/issues/476 
- https://github.com/vercel/next-learn/issues/484#issuecomment-1849731025

Solutions that will not work for me:
-adding POSTGRES_URL (it is specified as can be seen in stacktrace below)
- Using .env.development.local OR a .env.local file suggestion. These do NOT exist, I only had .env.example

```
npm run seed

> seed
> node -r dotenv/config ./scripts/seed.js

node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND ep-icy-cell-a47ky353-pooler.us-east-1.postgres.vercel-storage.com
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (C:\work\projects\nextjs-dashboard\node_modules\ws\lib\websocket.js:1016:13)
    at ClientRequest.<anonymous> (C:\work\projects\nextjs-dashboard\node_modules\ws\lib\websocket.js:864:5)
    at ClientRequest.emit (node:events:518:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'ep-icy-cell-a47ky353-pooler.us-east-1.postgres.vercel-storage.com'
}

Node.js v20.11.0
```


Ideas?

**Comment by thda** [comment] 2024-01-31 22:02
I'm facing the same issue on a Mac M1 with postgresql installed using brew and POSTGRES_URL properly set (ie I can connect using psql with the same url)

**Comment by warrengoldman** [comment] 2024-02-01 00:11
attached a version of data.ts that is an avoidance of the database (and the database issue). Might be useful until someone solves what this problem is.
[data.txt](https://github.com/vercel/next-learn/files/14118695/data.txt)

**Comment by Niskarsh12** [comment] 2024-02-01 13:19
> Hi !
> 
> Just rename .env.local to .env worked for me

Thanks , it worked for me too 
I was stuck for  atleast 1 hour coz of this problem 🙃

**Comment by warrengoldman** [comment] 2024-02-02 15:41
> > Hi !
> > Just rename .env.local to .env worked for me
> 
> Thanks , it worked for me too I was stuck for atleast 1 hour coz of this problem 🙃

I have no .env.local, I had .env.example, which I renamed to .env (as per the tutorial). This did NOT fix it.

**Comment by Niskarsh12** [comment] 2024-02-02 15:47
> > > Hi !
> > > Just rename .env.local to .env worked for me
> > 
> > 
> > Thanks , it worked for me too I was stuck for atleast 1 hour coz of this problem 🙃
> 
> I have no .env.local, I had .env.example, which I renamed to .env (as per the tutorial). This did NOT fix it.

share the screeshot if you can

**Comment by warrengoldman** [comment] 2024-02-02 15:55
> > > > Hi !
> > > > Just rename .env.local to .env worked for me
> > > 
> > > 
> > > Thanks , it worked for me too I was stuck for atleast 1 hour coz of this problem 🙃
> > 
> > 
> > I have no .env.local, I had .env.example, which I renamed to .env (as per the tutorial). This did NOT fix it.
> 
> share the screeshot if you can

See https://github.com/vercel/next-learn/issues/484#issuecomment-1920045791 for details

**Comment by HadeedShahid** [comment] 2024-03-02 18:18
@daweed311  did you find any solution for this?

**Comment by warrengoldman** [comment] 2024-03-03 00:25
no just used static file (to avoid db usage)  i attached to issue.

**Comment by daweed311** [comment] 2024-03-04 08:18
> @daweed311 did you find any solution for this?

Unfortunately, no.
I completed this tutorial on a Windows device.

**Comment by openSourceBugs** [comment] 2024-03-10 00:13
The sql is all wrong.  

const users = [
  {
    id: '410544b2-4001-4271-9855-fec4b6a6442a',
    name: 'User',
    email: 'user@nextmail.com',
    password: '123456',
  },
];

Attempting to insert this data leads to 
An error occurred while attempting to seed the database: error: trailing junk after numeric literal at or near "410544b"

The database tables are not being set up correctly

**Comment by alfredozorrilla** [comment] 2024-03-15 12:34
Yes, @openSourceBugs comment is correct.

You need to take 2 steps to fix it:

1. Use double quotations in the `placeholder-daja.js` JSON values (as shown below), because the Template Literals (backticks) strings on the `seed.js` queries are being rendered without single quotes in the values, so they fail. I've attached the fixed JS file, and a snippet below if you wanna do it by hand.

```
const users = [
  {
    id: "'410544b2-4001-4271-9855-fec4b6a6442a'",
    name: "'User'",
    email: "'user@nextmail.com'",
    password: "'123456'",
  },
];
```

2. `hashedPassword` is a calculated value (doesn't come from the placeholders) so it needs to be fixed in situ: `\'${hashedPassword}\'` (by adding single quotation marks on `seed.js`)

Optional:

If you are trying to run the tutorial without connecting to Vercel's cloud, and the `@vercel/postgres` database client is giving you problems, you can replace it completely with `node-postgres`.

Just install it with `npm install node-postgres` then import it in replacement of Vercel's:

```
//const { db } = require('@vercel/postgres');
const { Client } = require('pg');
const client = new Client({
    user: 'postgres',
    password: 'PASSWORD',
    host: 'localhost',
    port: '5432',
    database: 'nextjs-dashboard-postgres',
});
```

If you don't set the Config dictionary, it will take the environment variables, just like Vercel's.

And replace all the `client.sql` with `client.query(...)` in `seed.js` like this:

```
    await client.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
    // Create the "users" table if it doesn't exist
    const createTable = await client.query(`
      CREATE TABLE IF NOT EXISTS users (
        id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email TEXT NOT NULL UNIQUE,
        password TEXT NOT NULL
      );
    `);
```

And finally, fix the main function:

```
async function main() {
  await client.connect();

  await seedUsers(client);
  await seedCustomers(client);
  await seedInvoices(client);
  await seedRevenue(client);

  await client.end();
}
```

These changes made the trick for me.

Cheers!

[placeholder-data.js.txt](https://github.com/vercel/next-learn/files/14615308/placeholder-data.js.txt)


> The sql is all wrong.
> 
> const users = [ { id: '410544b2-4001-4271-9855-fec4b6a6442a', name: 'User', email: '[user@nextmail.com](mailto:user@nextmail.com)', password: '123456', }, ];
> 
> Attempting to insert this data leads to An error occurred while attempting to seed the database: error: trailing junk after numeric literal at or near "410544b"
> 
> So basically, the placeholder-js data needs to be sanitized and not evalulate to something else. Postgres is thinking that subtraction is being done due to absence of correct quotes.

**Comment by GodNoden** [comment] 2024-03-30 08:29
> Yes, @openSourceBugs comment is correct.
> 
> You need to take 2 steps to fix it:
> 
> 1. Use double quotations in the `placeholder-daja.js` JSON values (as shown below), because the Template Literals (backticks) strings on the `seed.js` queries are being rendered without single quotes in the values, so they fail. I've attached the fixed JS file, and a snippet below if you wanna do it by hand.
> 
> ```
> const users = [
>   {
>     id: "'410544b2-4001-4271-9855-fec4b6a6442a'",
>     name: "'User'",
>     email: "'user@nextmail.com'",
>     password: "'123456'",
>   },
> ];
> ```
> 
> 2. `hashedPassword` is a calculated value (doesn't come from the placeholders) so it needs to be fixed in situ: `\'${hashedPassword}\'` (by adding single quotation marks on `seed.js`)
> 
> Optional:
> 
> If you are trying to run the tutorial without connecting to Vercel's cloud, and the `@vercel/postgres` database client is giving you problems, you can replace it completely with `node-postgres`.
> 
> Just install it with `npm install node-postgres` then import it in replacement of Vercel's:
> 
> ```
> //const { db } = require('@vercel/postgres');
> const { Client } = require('pg');
> const client = new Client({
>     user: 'postgres',
>     password: 'PASSWORD',
>     host: 'localhost',
>     port: '5432',
>     database: 'nextjs-dashboard-postgres',
> });
> ```
> 
> If you don't set the Config dictionary, it will take the environment variables, just like Vercel's.
> 
> And replace all the `client.sql` with `client.query(...)` in `seed.js` like this:
> 
> ```
>     await client.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
>     // Create the "users" table if it doesn't exist
>     const createTable = await client.query(`
>       CREATE TABLE IF NOT EXISTS users (
>         id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
>         name VARCHAR(255) NOT NULL,
>         email TEXT NOT NULL UNIQUE,
>         password TEXT NOT NULL
>       );
>     `);
> ```
> 
> And finally, fix the main function:
> 
> ```
> async function main() {
>   await client.connect();
> 
>   await seedUsers(client);
>   await seedCustomers(client);
>   await seedInvoices(client);
>   await seedRevenue(client);
> 
>   await client.end();
> }
> ```
> 
> These changes made the trick for me.
> 
> Cheers!
> 
> [placeholder-data.js.txt](https://github.com/vercel/next-learn/files/14615308/placeholder-data.js.txt)
> 
> > The sql is all wrong.
> > const users = [ { id: '410544b2-4001-4271-9855-fec4b6a6442a', name: 'User', email: '[user@nextmail.com](mailto:user@nextmail.com)', password: '123456', }, ];
> > Attempting to insert this data leads to An error occurred while attempting to seed the database: error: trailing junk after numeric literal at or near "410544b"
> > So basically, the placeholder-js data needs to be sanitized and not evalulate to something else. Postgres is thinking that subtraction is being done due to absence of correct quotes.

Jesus, thank you man, underrated comment

**Comment by Offado** [comment] 2024-04-12 21:51
Comment ajoutées des données à la base de données vercel/postgres lors d'une sumission de formulaire

**Comment by shuvo-me** [comment] 2024-04-26 06:36
@daweed311 hey there! I have solved this by changing the node version according to package.json.
![image](https://github.com/vercel/next-learn/assets/61267686/8040c52e-43f7-4987-98c8-384f740f34ec)

**Comment by PJW980921** [comment] 2024-05-01 09:10
file name Edit  .env.example -> .env

**Comment by dakshika** [comment] 2024-05-26 16:22
still this isn't working on MacOs

**Comment by sanwinmaung** [comment] 2024-06-19 21:15
> Hi !
> 
> Just rename .env.local to .env worked for me

It's worked for me! Thanks.

**Comment by abdulrehman3725** [comment] 2024-06-23 19:28
@daweed311  just you need to update the node version 

It worked for me

**Comment by leerob** [comment] 2024-06-23 22:52
I am not able to reproduce this. Please open a new issue if you are still having trouble here. Thank you!

We are also making the seeding easier in this PR by allowing you to hit a URL in the browser: https://github.com/vercel/next-learn/pull/764

**Closed by leerob** 2024-06-23 22:52 UTC

**Comment by kupietools** [comment] 2024-10-09 06:12
Months later, this is still an issue on MacOS.

**Comment by abdulrehman3725** [comment] 2024-10-09 08:43
> Months later, this is still an issue on MacOS.

see their learning chapter 6 again. https://nextjs.org/learn/dashboard-app/setting-up-your-database

Actually they keep on updating
