### ISSUE TITLE
Cannot find package

### ISSUE THREAD

**Issue by ethan-grzeda** [vercel/next-learn#168] opened 2023-09-19 17:31 UTC
I tried installing with every command suggestion, without being connected to a VPN, and I got this same error every time:

`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/next/-/next-13.5.0.tgz - Not found
npm ERR! 404
npm ERR! 404  'next@https://registry.npmjs.org/next/-/next-13.5.0.tgz' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
`
I am running node version 18.17.1 on Windows 10.

**Comment by manovotny** [comment] 2023-09-19 17:41
Closing as duplicate of #167.

**Closed by manovotny** 2023-09-19 17:41 UTC
