### ISSUE TITLE
Chapter 15 Adding Authentication - Login does work; no redirect to /dashboard

### ISSUE THREAD

**Issue by neslob** [vercel/next-learn#252] opened 2023-10-27 22:30 UTC
Followed chapter 15, but I could not test login. No direct to /dashboard.

Also tried [https://github.com/vercel/next-learn/tree/main/dashboard/final-example](https://github.com/vercel/next-learn/tree/main/dashboard/final-example).

Same behaviour. 

Added `console.log` to `app/lib/actions.ts`

```typescript
// auth.js
...
export const { auth, signIn, signOut } = NextAuth({
  ...authConfig,
  providers: [
    Credentials({
      async authorize(credentials) {
        const parsedCredentials = z
          .object({ email: z.string().email(), password: z.string().min(6) })
          .safeParse(credentials);

        if (parsedCredentials.success) {
          const { email, password } = parsedCredentials.data;

          const user = await getUser(email);
          if (!user) return null;

          const passwordsMatch = await bcrypt.compare(password, user.password);
          if (passwordsMatch) {
            console.log('Successfully authenticated user:', user);
            return user;
          } 
        }

        console.log('Invalid credentials');
        return null;
      },
    }),
  ],
});
```

```typescript
// app/lib/actions.ts
...
export async function authenticate(
  prevState: string | undefined,
  formData: FormData,
) {
  try {
    await signIn('credentials', Object.fromEntries(formData));
  } catch (error) {
    console.log('actions.ts authenticate error', error);
    if ((error as Error).message.includes('CredentialsSignin')) {
      return 'CredentialsSignin';
    }
    throw error;
  }
}
```

```shell
Successfully authenticated user: {
  id: '410544b2-4001-4271-9855-fec4b6a6442a',
  name: 'User',
  email: 'user@nextmail.com',
  password: '$2b$10$6zgMX3nExd6v9xRz795UbuKs5solgeTcw3JJljmvFM2V.AOGp.Mca'
}
actions.ts authenticate error Error: NEXT_REDIRECT
    at getRedirectError (webpack-internal:///(action-browser)/./node_modules/next/dist/client/components/redirect.js:44:19)
    at redirect (webpack-internal:///(action-browser)/./node_modules/next/dist/client/components/redirect.js:54:11)
    at signIn (webpack-internal:///(action-browser)/./node_modules/next-auth/lib/actions.js:63:89)
    at async authenticate (webpack-internal:///(action-browser)/./app/lib/actions.ts:134:9)
    at async /Users/nils/temp/next-learn/next-learn/dashboard/final-example/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:38:479
    at async tK (/Users/nils/temp/next-learn/next-learn/dashboard/final-example/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:37:4768)
    at async ri (/Users/nils/temp/next-learn/next-learn/dashboard/final-example/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:38:28891)
    at async doRender (/Users/nils/temp/next-learn/next-learn/dashboard/final-example/node_modules/next/dist/server/base-server.js:1340:26)
    at async cacheEntry.responseCache.get.incrementalCache.incrementalCache (/Users/nils/temp/next-learn/next-learn/dashboard/final-example/node_modules/next/dist/server/base-server.js:1500:28)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/nils/temp/next-learn/next-learn/dashboard/final-example/node_modules/next/dist/server/base-server.js:1408:28)
    at async DevServer.renderPageComponent (/Users/nils/temp/next-learn/next-learn/dashboard/final-example/node_modules/next/dist/server/base-server.js:1760:24)
    at async DevServer.renderToResponseImpl (/Users/nils/temp/next-learn/next-learn/dashboard/final-example/node_modules/next/dist/server/base-server.js:1798:32)
    at async DevServer.pipeImpl (/Users/nils/temp/next-learn/next-learn/dashboard/final-example/node_modules/next/dist/server/base-server.js:851:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/nils/temp/next-learn/next-learn/dashboard/final-example/node_modules/next/dist/server/next-server.js:266:17)
    at async DevServer.handleRequestImpl (/Users/nils/temp/next-learn/next-learn/dashboard/final-example/node_modules/next/dist/server/base-server.js:748:17) {
  digest: 'NEXT_REDIRECT;replace;http://localhost:3001/login?callbackUrl=http%3A%2F%2Flocalhost%3A3001%2Flogin;false',
  mutableCookies: p {
    _parsed: Map(2) {
      'next-auth.callback-url' => [Object],
      'next-auth.session-token' => [Object]
    },
    _headers: HeadersList {
      cookies: [Array],
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}
```

I am stuck.

**Comment by Kayoshi-dev** [comment] 2023-10-27 22:33
It seems the auth.user object doesn't get populated correctly with the data

**Comment by robbmerritt** [comment] 2023-10-27 22:36
Lol, I just posted this issue also.

**Comment by neslob** [comment] 2023-10-27 22:51
got it working. 

Need to add `NEXTAUTH_URL=http://localhost:3000` to `.env`

```
#.env
NEXTAUTH_URL=http://localhost:3000
```

**Comment by robbmerritt** [comment] 2023-10-27 23:45
> Got it 1/2 working to get to /dashboard and do the sign-in, sign-out dance.
> 
> Need to add `NEXTAUTH_URL=http://localhost:3000` to `.env`
> 
> ```
> #.env
> NEXTAUTH_URL=http://localhost:3000
> ```
> 
> This should be added to the documentation.
> 
> But, the error `actions.ts authenticate error Error: NEXT_REDIRECT` persists.

It does work if you add the NEXTAUTH_URL to your .encv.

I think there is a known issue for calling `redirect` inside a try/catch.
The code is doing that here.

It calls `signIn` from `NextAuth`, which calls a `redirect`.
The call to `signIn` is wrapped in a try/catch:

```
export async function authenticate(
  prevState: string | undefined,
  formData: FormData,
) {
  try {
    console.log('formData', formData);
    await signIn('credentials', Object.fromEntries(formData));
  } catch (error) {
    console.log('error', error);
    if ((error as Error).message.includes('CredentialsSignin')) {
      return 'CredentialSignin';
    }
    throw error;
  }
}
```

If I tell `signIn` not to redirect and call the redirect in the finally block, the error goes away.
```
export async function authenticate(
  prevState: string | undefined,
  formData: FormData,
) {
  let responseRedirectUrl = null;
  try {
    console.log('formData', formData);
    responseRedirectUrl = await signIn('credentials', {
      ...Object.fromEntries(formData),
      redirect: false,
    });
  } catch (error) {
    console.log('error', error);
    if ((error as Error).message.includes('CredentialsSignin')) {
      return 'CredentialSignin';
    }
    throw error;
  } finally {
    if (responseRedirectUrl) redirect(responseRedirectUrl);
  }
}
```

**Comment by AlistairFR** [comment] 2023-10-29 21:12
Adding `NEXTAUTH_URL` to my .env + calling the redirect in the finally block resolved it for me, works everytime, thanks ! But I can confirm that the error is still thrown in the console at login.

**Comment by robbmerritt** [comment] 2023-10-30 02:39
> Adding `NEXTAUTH_URL` to my .env + calling the redirect in the finally block resolved it for me, works everytime, thanks ! But I can confirm that the error is still thrown in the console at login.

Also, clear out all memory (cache)... Mine was not working immediately, after adding `NEXTAUTH_URL`, and I went nuclear... cleared everything.

I think the issue that should be addressed here, is why an intentional  "redirect" would throw an error?  Should this be an intentional error?

**Comment by robbmerritt** [comment] 2023-10-30 03:34
I think it is confusing that an intentional `redirect` in NextJs could be considered an Error?  It is sort of between an error and success, right?

**Comment by robbmerritt** [comment] 2023-10-30 03:46
> Adding `NEXTAUTH_URL` to my .env + calling the redirect in the finally block resolved it for me, works everytime, thanks ! But I can confirm that the error is still thrown in the console at login.

I think an intentional redirect is intended to throw an error. It's intention confused me.

**Comment by delbaoliveira** [comment] 2023-11-14 14:43
Hey there! The `NEXTAUTH_URL` env variable is no longer required, as it was fixed in Next.js. Updating to the latest should fix it.  

PR: https://github.com/vercel/next-learn/pull/441

**Closed by delbaoliveira** 2023-11-14 14:43 UTC

**Comment by fanhefeng** [comment] 2025-03-14 04:07
I deployed my project to vercel. I found a same question.
https://github.com/fanhefeng/nextjs-dashboard

![Image](https://github.com/user-attachments/assets/862bd35c-73c6-42a3-8d7b-b1cef11441e5)
