### ISSUE TITLE
Chapter 6: no postgres option available

### ISSUE THREAD

**Issue by yi7242** [vercel/next-learn#925] opened 2024-11-17 13:49 UTC
In chapter 6, [we are instructed to setup a Postgres database](https://nextjs.org/learn/dashboard-app/setting-up-your-database#create-a-postgres-database).
But currently, there is no postgres option available without using Neon. 
![image](https://github.com/user-attachments/assets/145a4229-042b-4b20-bf01-6259952493de)

It seems that the information is outdated and should be updated.

**Comment by PotashinAndrey** [comment] 2024-11-17 14:40
For me it works with Neon right now.

**Comment by yi7242** [comment] 2024-11-17 17:18
> For me it works with Neon right now.
I understand that doing a similar procedure can work in Neon, but I was confused by the slightly different procedures for creating databases and viewing tables in Neon.
I think it is appropriate to update the info.

**Comment by nitronaj** [comment] 2024-11-19 09:52
I encountered the same issue, but after checking the [Vercel documentation-Neon partnership](https://vercel.com/docs/storage/vercel-postgres#neon-partnership), I found out that Vercel now has a partnership with Neon. Moving forward, it’s recommended to use Neon Postgres for storage with Vercel.

**Comment by delbaoliveira** [comment] 2024-11-19 11:43
Hey! Yes, the Vercel Postgres option is being replaced with the Neon integration option. You won't see the old option if you've recently created a Vercel account. We're updating Chapter 6 to reflect these changes, and recently merged a PR that'll allow you to query the database using a Route Handler since the query UI is not available:  https://github.com/vercel/next-learn/pull/927

We're also testing the Supabase integration with this project, so that in the future you'll be able to choose between Neon or Supabase.

**Closed** 2024-11-19 11:44 UTC

**Comment by drichelson** [comment] 2024-11-24 06:58
>We're also testing the Supabase integration with this project, so that in the future you'll be able to choose between Neon or Supabase.

As of 11/24/2024 I can confirm that the project does not work when using Supabase (fails with 404 when calling `fetchRevenue()` in Chapter 7 

When switching to Neon it works (up to Chapter 7's `fetchRevenue()` call.. I haven't proceeded any farther)
