### ISSUE TITLE
Chapter 6: 'missing_connection_string':

### ISSUE THREAD

**Issue by meiyizheng** [vercel/next-learn#768] opened 2024-06-25 09:45 UTC
I followed exactly the tutorial. I met an issue when doing the chapter 6 and trying to deploy on the vercel. The error is : 

tl [VercelPostgresError]: VercelPostgresError - 'missing_connection_string': You did not supply a 'connectionString' and no 'POSTGRES_URL' env var was found.
    at tf (/vercel/path0/.next/server/app/seed/route.js:60:5026)
    at Object.get (/vercel/path0/.next/server/app/seed/route.js:60:6072)
    at /vercel/path0/.next/server/app/seed/route.js:1:3956
    at t.a (/vercel/path0/.next/server/webpack-runtime.js:1:866)
    at 1507 (/vercel/path0/.next/server/app/seed/route.js:1:3849)
    at t (/vercel/path0/.next/server/webpack-runtime.js:1:127)
    at /vercel/path0/.next/server/app/seed/route.js:1:1176
    at t.a (/vercel/path0/.next/server/webpack-runtime.js:1:866)
    at 5064 (/vercel/path0/.next/server/app/seed/route.js:1:967)
    at t (/vercel/path0/.next/server/webpack-runtime.js:1:127) {
  code: 'missing_connection_string'
}
> Build error occurred
Error: Failed to collect page data for /seed
    at /vercel/path0/node_modules/.pnpm/next@15.0.0-rc.0_react-dom@19.0.0-rc-f994737d14-20240522_react@19.0.0-rc-f994737d14-20240522/node_modules/next/dist/build/utils.js:1274:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run build" exited with 1

**Comment by talimami** [comment] 2024-06-25 22:43
try putting require('dotenv').config();
in the script.js folder

**Comment by A-Marotta** [comment] 2024-06-25 23:09
Yeah I had the same issue and found the following workaround by deleting the seed directory, then committing my code to GitHub, which triggered a redeployment on Vercel.

Chapter 6 outlines the steps to seed the data locally, so the seed directory and route.ts really don’t need to be committed and included as part of the build process which is triggering a fail because we do not have those psql env vars yet - the guide mentions deleting it after a successful seed anyway.

**Comment by meiyizheng** [comment] 2024-06-25 23:36
> Yeah I had the same issue and found the following workaround by deleting the seed directory, then committing my code to GitHub, which triggered a redeployment on Vercel.
> 
> Chapter 6 outlines the steps to seed the data locally, so the seed directory and route.ts really don’t need to be committed and included as part of the build process which is triggering a fail because we do not have those psql env vars yet - the guide mentions deleting it after a successful seed anyway.

Thanks. It solved.

**Comment by AjayUppari** [comment] 2024-06-29 10:48
Thanks @A-Marotta it worked

**Comment by ndimoforaretas** [comment] 2024-06-29 13:36
What solved this for me was that I:
- Created the postgres app on vercel
- added the credentials to the local .env file
- then added ALL the enviroment variables to the "Environment Variables" settings on vercel
- redeployed and it worked.

**Comment by JaredMalan7** [comment] 2024-06-29 19:04
@ndimoforaretas did you not include the AUTH_URL, AUTH_SECRET?

**Comment by ndimoforaretas** [comment] 2024-06-29 19:11
> @ndimoforaretas did you not include the AUTH_URL, AUTH_SECRET?

Hi @JaredMalan7 , at this point, it was not being used.
But during chapter 15 it is then added.👌🏼

Cheers.

**Comment by vincent-bru** [comment] 2024-06-30 17:46
> Yeah I had the same issue and found the following workaround by deleting the seed directory, then committing my code to GitHub, which triggered a redeployment on Vercel.
> 
> Chapter 6 outlines the steps to seed the data locally, so the seed directory and route.ts really don’t need to be committed and included as part of the build process which is triggering a fail because we do not have those psql env vars yet - the guide mentions deleting it after a successful seed anyway.

thank you so much

**Comment by nguyenmp** [comment] 2024-07-03 21:05
Looks like a regression from https://github.com/vercel/next-learn/pull/764/commits/842990e8e803bf435078cb836a06c862ac5d1a66#diff-c1bb994d2abe252301b932741da17eb099b2a377c567a9e2ede112b0d6697881

Code was originally in dashboard/final-example/scripts/seed.js which wasn't bundled but was moved to dashboard/final-example/app/seed/route.ts which is bundled, causing us to depend on "@vercel/postgres" which is undefined at the time of the tutorial so the build fails.

**Comment by leerob** [comment] 2024-07-06 03:22
Fixed! With more specific guidance in the written part to uncomment, run it, then delete it.

https://github.com/vercel/next-learn/commit/d379162091cac7ea4d0e3054a9fb527c00596264

**Closed by leerob** 2024-07-06 03:22 UTC
