### ISSUE TITLE
Bcrypt doesn't work , replace it with bcryptjs

### ISSUE THREAD

**Issue by primedev88** [vercel/next-learn#684] opened 2024-05-16 19:07 UTC

**Comment by destinedcodes** [comment] 2024-06-08 07:44
```
npm uninstall bcrypt
npm install bcrypt
```
This fixed the issue I faced with bcrypt when seeding the database

**Comment by leerob** [comment] 2024-06-23 21:10
Closing since the reinstall seems to work for you! I can confirm bcrypt should be okay.

**Closed by leerob** 2024-06-23 21:10 UTC

**Comment by carlaiau** [comment] 2025-02-13 21:46
bcrypt does not work if you follow the tutorial and try to deploy. This is prior to seeding

```
[Error: Cannot find module '/vercel/path0/node_modules/.pnpm/bcrypt@5.1.1/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node'
Require stack:
- /vercel/path0/node_modules/.pnpm/bcrypt@5.1.1/node_modules/bcrypt/bcrypt.js
- /vercel/path0/.next/server/app/seed/route.js
- /vercel/path0/node_modules/.pnpm/next@15.1.6_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/server/require.js
- /vercel/path0/node_modules/.pnpm/next@15.1.6_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/server/load-components.js
- /vercel/path0/node_modules/.pnpm/next@15.1.6_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/build/utils.js
- /vercel/path0/node_modules/.pnpm/next@15.1.6_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/build/worker.js
- /vercel/path0/node_modules/.pnpm/next@15.1.6_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/next/dist/compiled/jest-worker/processChild.js] {
code: 'MODULE_NOT_FOUND',
requireStack: [Array]
}
```
